### ISSUE TITLE
Automatic Deployments to GitHub Pages

### ISSUE THREAD

**Issue by GaryPWhite** [wayfair/wayfair.github.io#2]
### Description
When a merge happens to the `main` branch as of now, no action takes place.

It would be convenient to deploy our site to `gh-pages` (the branch, and the thing) whenever a merge to `main` takes place. This can be done with GitHub Actions.

### TODO

- [ ] Find GitHub Action / container image that supports `gatsby build`
- [ ] Find GitHub Action / container image that supports deploying to github pages
- [ ] Put the two together, and run on any push to `main`

**Comment by jashparekh** [comment]
@GaryPWhite - Is anyone working on this? If not, I would like to volunteer ✋🏻
